name: CI and Deploy to Space

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Optional static analysis
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy
      - name: Run ruff
        run: ruff check backend
      - name: Run mypy
        run: mypy backend

  test-and-build:
    name: Backend tests and frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt pytest
      - name: Run pytest
        run: pytest backend/tests
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install frontend dependencies
        run: npm ci
      - name: Build frontend
        run: npm run build

  deploy:
    name: Push application to Space
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Hugging Face Space
        uses: huggingface/space-pusher@v1
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          space-id: ${{ secrets.HF_SPACE_ID }}
          commit-message: Deploy ${{ github.sha }}
