name: CI and Deploy to Hugging Face Space

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Static Analysis (Optional)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Run ruff
        run: ruff check backend

      - name: Run mypy
        run: mypy backend

  test-and-build:
    name: Backend tests and frontend build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt pytest
          
      - name: Create writable data directory for tests
        run: mkdir -p data/uploads

      - name: Run pytest
        run: pytest backend/tests

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

  deploy:
    name: Push application to Hugging Face Space
    runs-on: ubuntu-latest
    needs: test-and-build
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: deploy-space
      cancel-in-progress: true
    steps:
      - name: Checkout repository (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - name: Initialize Git LFS
        run: |
          git lfs install
          git lfs track "*.db" "*.bin" "*.pt" "*.safetensors"
          git add .gitattributes
          git diff --cached --quiet || git commit -m "Ensure LFS tracking" || echo "No LFS changes"

      - name: Push to Hugging Face Space
        uses: huggingface/space-pusher@v1
        with:
          repo-token: ${{ secrets.HF_TOKEN }}
          space-id: medjotavesf/NexusQuantumI2A2
          commit-message: "Deploy ${{ github.sha }}"

      - name: Summary
        run: |
          echo "✅ Deploy concluído com sucesso!" >> $GITHUB_STEP_SUMMARY
          echo "🔗 Space: https://huggingface.co/spaces/medjotavesf/NexusQuantumI2A2" >> $GITHUB_STEP_SUMMARY
          echo "📦 Commit: $GITHUB_SHA" >> $GITHUB_STEP_SUMMARY
